version: "3"

services:
  app:
    container_name: consulta_cep_ms
    build: .
    #image: israelbuiatti/consulta-cep-ms
    ports:
      - "3333:3333"
    command: npm start
    environment:
      - NODE_ENV=production
      - PORT=3333
      - DB_HOST=ec2-3-95-87-221.compute-1.amazonaws.com
      - DB_USER=letijqgofvwczj
      - DB_PASSWORD=5d4fce0fab728c63f1828aed4fb66266424806a72e968e2e730a95d8e9a07172
      - DB_DATABASE=d4baq2lup3gb3t
      - DB_PORT=5432
      - DB_SSL=true
      - REDIS_HOST=ec2-52-5-186-198.compute-1.amazonaws.com
      - REDIS_PORT=18849
      - REDIS_USER=h
      - REDIS_PASS=pe012cdbe7b5a027ef463a54155c8ffb2e950f9ba296601237c99750750d2df7c
      - APP_SECRET=abcabc
