version: "3"

services:
  app:
    container_name: backend_ms
    build: .
    #image: israelbuiatti/ms-backend
    ports:
      - "3333:3333"
    command: npm start
    environment:
      - NODE_ENV=production
      - PORT=3333
      - DB_HOST=ec2-3-95-87-221.compute-1.amazonaws.com
      - DB_USER=letijqgofvwczj
      - DB_PASSWORD=5d4fce0fab728c63f1828aed4fb66266424806a72e968e2e730a95d8e9a07172
      - DB_DATABASE=d4baq2lup3gb3t
      - DB_PORT=5432
      - DB_SSL=true
      - REDIS_HOST=buiatte.com.br
      - REDIS_PORT=6379
      - REDIS_USER=
      - REDIS_PASS=
      - APP_SECRET=abcabc
