version: '3.7'
services: 
  frontend-php:
    build: .
    container_name: 'frontend-php'
    image: 'frontend-php'
    ports:
      - 88:80
    volumes:
      - ./www:/var/www/html
    environment:
      - URL_BASE=http://localhost:88
      - URL_API=http://localhost:3333
